### ISSUE TITLE
Default value is "yes"; suggest program only runs with user input 

### ISSUE THREAD

**Issue by wrongkindofdoctor** [GFDL-Eric/valentineFortran#2]
I compiled and ran the program and it returned "YES". Now I'm cranky.

**Comment by GFDL-Eric** [comment]
Did you change the parameter? Tom has a PR in so that the parameter is specified by the user... you can always set it to 0.999 (or .ge. 1 if you never want to see "yes")

**Comment by wrongkindofdoctor** [comment]
I tried a value of 1e20 to represent my boundless hatred of Fortran. It returned "NO!!". I am okay now.
